version: '3'
services:
  order-processor:
    build: order-processor
    ports:
      - "8000:8000"
    environment:
      ZIPKIN_BASE_URL: http://zipkin:9411/
      ZIPKIN_SAMPLER_PERCENTAGE: 1.0
      MIN_DELAY_MS: 20
      READ_TIMEOUT_MS: 1000
      FAILURE_RATE_TO_SIMULATE: 0.2
      USE_SERVICE_BASED_URLS: "true"
  payment-gateway:
    build: payment-gateway
    ports:
      - "8001:8001"
    environment:
      ZIPKIN_BASE_URL: http://zipkin:9411/
      ZIPKIN_SAMPLER_PERCENTAGE: 1.0
      MIN_DELAY_MS: 20
      READ_TIMEOUT_MS: 1000
      FAILURE_RATE_TO_SIMULATE: 0.2
      USE_SERVICE_BASED_URLS: "true"
  inventory-reservation:
    build: inventory-reservation
    ports:
      - "8002:8002"
    environment:
      ZIPKIN_BASE_URL: http://zipkin:9411/
      ZIPKIN_SAMPLER_PERCENTAGE: 1.0
      MIN_DELAY_MS: 20
      READ_TIMEOUT_MS: 1000
      FAILURE_RATE_TO_SIMULATE: 0.2
      USE_SERVICE_BASED_URLS: "true"
  shipment:
    build: shipment
    ports:
      - "8003:8003"
    environment:
      ZIPKIN_BASE_URL: http://zipkin:9411/
      ZIPKIN_SAMPLER_PERCENTAGE: 1.0
      MIN_DELAY_MS: 20
      READ_TIMEOUT_MS: 1000
      FAILURE_RATE_TO_SIMULATE: 0.2
      USE_SERVICE_BASED_URLS: "true"
  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
